Updated GitHub Actions pipeline code

diff --git a/.github/workflows/codepipeline-monitor.yml b/.github/workflows/codepipeline-monitor.yml
--- a/.github/workflows/codepipeline-monitor.yml
+++ b/.github/workflows/codepipeline-monitor.yml
@@ -1,3 +1,10 @@
+# Before running the github actions pipeline you must configure the 
+# secrets in the github configuration. The variables that must be 
+# configured are:
+# CODEPIPELINE_NAME
+# REGION
+# ARN_ROLE_TO_ASSUME
+
 name: CodePipeline Monitor
 on:
     push:
@@ -22,26 +29,24 @@ jobs:
 
       - name: Get CodePipeline status
         run: |
-            execution_id=$(aws codepipeline list-pipeline-executions --pipeline-name ${{ secrets.CODEPIPELINE_NAME }} --query 'pipelineExecutionSummaries[0].pipelineExecutionId' --output text)
-  
+          execution_id=$(aws codepipeline list-pipeline-executions --pipeline-name ${{ secrets.CODEPIPELINE_NAME }} --query 'pipelineExecutionSummaries[0].pipelineExecutionId' --output text)
+          # Wait until the pipeline execution is finished.
+          while true; do
+              execution_status=$(aws codepipeline get-pipeline-execution --pipeline-name ${{ secrets.CODEPIPELINE_NAME }} --pipeline-execution-id $execution_id --query 'pipelineExecution.status' --output text)
 
-            # Wait until the pipeline execution is finished.
-            while true; do
-                execution_status=$(aws codepipeline get-pipeline-execution --pipeline-name ${{ secrets.CODEPIPELINE_NAME }} --pipeline-execution-id $execution_id --query 'pipelineExecution.status' --output text)
+              if [[ $execution_status == "InProgress" ]]; then
+                  echo "Execution in progress..."
+                  sleep 3  
+              elif [[ $execution_status == "Succeeded" ]]; then
+                  echo "Successful AWS CodePipeline execution!"
+                  break
+              else
+                  echo "Pipeline execution failed: $execution_status"
+                  exit 1
+              fi
+          done
 
-                if [[ $execution_status == "InProgress" ]]; then
-                    echo "Execution in progress..."
-                    sleep 3  
-                elif [[ $execution_status == "Succeeded" ]]; then
-                    echo "Successful execution!"
-                    break
-                else
-                    echo "Pipeline execution failed: $execution_status"
-                    exit 1
-                fi
-            done
-
-            echo "Synchronization with CodePipeline successfully completed."
+          echo "Synchronization with CodePipeline successfully completed."
 
 
             
